//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marende.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class OstaliCijene
    {
        public int Id { get; set; }
        public decimal Mali { get; set; }
        public decimal Srednji { get; set; }
        public decimal Veliki { get; set; }
        public decimal Piletina { get; set; }
        public decimal PiletinaSir { get; set; }
        public decimal Hamburger { get; set; }
        public decimal Cheesburger { get; set; }
        public decimal Cevapi { get; set; }
        public decimal Pizza { get; set; }
    }
}
