//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marende.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class RizzoCijene
    {
        public int Id { get; set; }
        public decimal Mali { get; set; }
        public decimal MaliSirSunka { get; set; }
        public decimal MaliPurecaDimljena { get; set; }
        public decimal MaliBudolaZimskaPrsutKulen { get; set; }
        public decimal MaliTuna { get; set; }
        public decimal Veliki { get; set; }
        public decimal VelikiSirSunka { get; set; }
        public decimal VelikiPurecaMladiDimljena { get; set; }
        public decimal VelikiBudolaZimskaPrsutKulen { get; set; }
        public decimal VelikiTuna { get; set; }
        public decimal DodatakSir { get; set; }
        public decimal DodatakNapomena { get; set; }
        public decimal SezonskaSalata { get; set; }
        public decimal GrckaSalata { get; set; }
        public decimal TunjSalata { get; set; }
    }
}
